version: '3.3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    container_name: netflix-postgres
    image: "netflix/postgres:1.0.0"
    environment:
      - POSTGRES_PASSWORD=TGxCOWiDbpcwgSM
      - POSTGRES_USER=netflix_user
      - POSTGRES_DB=netflix
    ports:
      - "5432:5432"
    networks:
      netflix_network:
        aliases:
            - netflix-postgres.local
  dataset:
    build:
      context: ./dataset
      dockerfile: ./Dockerfile
    container_name: netflix-dataset
    image: "netflix/dataset:1.0.0"
    depends_on:
      - postgres
    networks:
      netflix_network:
        aliases:
          - netflix-dataset.local
networks:
  netflix_network:
    driver: bridge
